<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140401103547 extends AbstractMigration {

	/**
	 * Newsletter attachment relation
	 *
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE lelesys_plugin_newsletter_domain_model_n_11124_attachments_join (newsletter_newsletter VARCHAR(40) NOT NULL, media_document VARCHAR(40) NOT NULL, INDEX IDX_8631FD5F9390BC62 (newsletter_newsletter), INDEX IDX_8631FD5FD708A4C4 (media_document), PRIMARY KEY(newsletter_newsletter, media_document)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_plugin_newsletter_domain_model_n_11124_attachments_join ADD CONSTRAINT FK_8631FD5F9390BC62 FOREIGN KEY (newsletter_newsletter) REFERENCES lelesys_plugin_newsletter_domain_model_newsletter (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_plugin_newsletter_domain_model_n_11124_attachments_join ADD CONSTRAINT FK_8631FD5FD708A4C4 FOREIGN KEY (media_document) REFERENCES typo3_media_domain_model_document (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_plugin_newsletter_domain_model_newsletter DROP FOREIGN KEY FK_739A5FC647C4FAD6");
		$this->addSql("DROP INDEX IDX_739A5FC647C4FAD6 ON lelesys_plugin_newsletter_domain_model_newsletter");
		$this->addSql("ALTER TABLE lelesys_plugin_newsletter_domain_model_newsletter DROP attachments");
	}

	/**
	 * Remove newsletter attachment relation
	 *
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE lelesys_plugin_newsletter_domain_model_n_11124_attachments_join");
		$this->addSql("ALTER TABLE lelesys_plugin_newsletter_domain_model_newsletter ADD attachments VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_newsletter_domain_model_newsletter ADD CONSTRAINT FK_739A5FC647C4FAD6 FOREIGN KEY (attachments) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_739A5FC647C4FAD6 ON lelesys_plugin_newsletter_domain_model_newsletter (attachments)");
	}
}