<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180528011804 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('UPDATE lelesys_plugin_newsletter_domain_model_recipient_person SET gender=\'f\' WHERE gender=\'1\'');
        $this->addSql('UPDATE lelesys_plugin_newsletter_domain_model_recipient_person SET gender=\'m\' WHERE gender=\'0\'');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('UPDATE lelesys_plugin_newsletter_domain_model_recipient_person SET gender=\'1\' WHERE gender=\'f\'');
        $this->addSql('UPDATE lelesys_plugin_newsletter_domain_model_recipient_person SET gender=\'0\' WHERE gender=\'m\'');
    }
}